### ISSUE TITLE
Fails when non-opus codec is used

### ISSUE THREAD

**Issue by SISheogorath** [Johni0702/mumble-web#10]
I noticed that the client silently fails when another client sends a package that uses the CELT codec.

The main problem is that there is no disconnect message because the script aborts with an uncaught exception.

It would be nice if we could handle it in any way.

**Comment by Johni0702** [comment]
I've fixed parsing of packets containing Speex or CELT data in [mumble-streams ](https://github.com/Johni0702/mumble-streams) and changed it and [mumble-client](https://github.com/Johni0702/mumble-client) to emit an `unknown_codec` event on the MumbleClient instance instead of crashing if an unknown codec is encountered.
Any `error` events emitted by the en-/decoder streams will now also be forwarded to the MumbleClient instance.
The MumbleClient now also emits a `disconnected` event whenever the connection is closed (e.g. due to network failure, an error in the decoder or a call to MumbleClient#disconnect()) which can be used to automatically reconnect or at least notify the user.

I'll probably incorporate those changes into mumble-web sometime this week or the next one.
I'll also see if I can get the Speex and CELT codecs into [mumble-client-codecs-browser](https://github.com/Johni0702/mumble-client-codecs-browser) so you can actually hear people when those codecs  are used.
