### ISSUE TITLE
does it support positional audio?

### ISSUE THREAD

**Issue by Deudly** [Johni0702/mumble-web#109]

**Comment by Johni0702** [comment]
No, it does not.

The current `master` version could in theory do positional audio but there's really no way to position the user since the code in the browser by design has no access to applications running on the user's system, so the positional data received is simply discarded.
The `webrtc` version completely lacks support for positional audio, i.e. the server does not even transmit it to the client.

If you were thinking about integrating it on the same page as a browser-based game, then it's probably easiest to just use the game's positional data, that'd also have the advantage that visual and auditory position delay are the same.

**Comment by MuhammadAli-208** [comment]
@Johni0702  I have positional Data, However I want to send it to server along with audio packets. how I can do that specific thing ?
