### ISSUE TITLE
Adapt KiwiIRC Jitsi-meet plugin?

### ISSUE THREAD

**Issue by poVoq** [Johni0702/mumble-web#140]
Since it seems like the Matrix integration is using the Jitsi-meet function, how about modifying this KiwiIRC plugin to have similar functionality on KiwiIRC via mumble-web?

https://github.com/kiwiirc/plugin-conference

**Comment by poVoq** [comment]
I should add, KiwiIRC is the official webclient for Freenode IRC, so this could potentially have a massive user-base.

See https://webchat.freenode.net

**Comment by Johni0702** [comment]
The Matrix integration has almost nothing to do with Jitsi Meet.
It merely pretends to be a Jjitsi widget because that used to be the only way to get Element/Riot to allow it to ask for access to the microphone (all other widgets were denied by default) and to stay active when switching to a different chat (all other widgets were closed when you leave the chat). Both of these were hard-coded to only be allowed for the "jitsi" widget type (dunno if this has changed by now, haven't used it ever since I set it up) and that's about all it has to do with Jitsi Meet.
