### ISSUE TITLE
Inform users not to choose usernames with spaces?

### ISSUE THREAD

**Issue by r4dh4l** [Johni0702/mumble-web#165]
Hello,

providing a username with space characters (i.e. `John Doe`) mumble-web reports:

> Failed to connect  
> Your user name was rejected. Maybe try a different one?
The server reports:  
> "Invalid username"

Advanced users know that Mumble doesn't like usernames with spaces but newcomers would be irritated. Would it be possible to add a hint under the username field like

> Username [...]
> Hint: No space charakters allowed.

?

**Comment by Johni0702** [comment]
There is nothing in the Mumble protocol which would prevent usernames with spaces in them.
It's entirely up to the server to decide whether a given name is valid (spaces just happen to not be valid with the default murmur config) and there is no way for the client to know why it was rejected, so any more detailed explanation would also have to be sent by the server instead of just the generic "Invalid username".

See also https://github.com/mumble-voip/mumble/issues/1202 for space specifically.
