### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by streaps** [Johni0702/mumble-web#92]
I had success with the older version from npm, but the build from master (e008ef1) doesn't connect. This error appears in the console:

```
index.js:9
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ./node_modules/webworkify/index.js.module.exports (index.js:9)
    at ReusePool._factory (decoder-stream.js:36)
    at ReusePool../node_modules/reuse-pool/index.js.ReusePool.get (index.js:23)
    at Object../node_modules/mumble-client-codecs-browser/lib/decoder-stream.js (decoder-stream.js:39)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/mumble-client-codecs-browser/lib/index.js (index.js:13)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/mumble-client-codecs-browser/index.js (index.js:1)
    at __webpack_require__ (bootstrap:19)
```
Any idea what is wrong? I have no problems with the demo server voice.johni0702.de

**Comment by Johni0702** [comment]
Could you try to run `npm run postinstall` before running `npm run build` and see if that makes any difference?
So:
```
git clone https://github.com/johni0702/mumble-web
cd mumble-web
npm install
npm run postinstall
npm run build
```

The demo site hasn't been update in a while (hence why it's still working) cause I haven't built mumble-web myself any time recently (only been merging PRs).

**Comment by streaps** [comment]
That fixed the problem. Tokens are working now too. :)

There were a lot of warnings though:
https://gist.github.com/streaps/804577012a201c44f0375cd5d503667c

**Comment by Johni0702** [comment]
Hmm, it looks like `postinstall` isn't actually supposed to run when one runs `npm install` without any arguments ([ref](https://docs.npmjs.com/misc/scripts)), and `patch-package` does recommend one execute it during `postinstall` ([ref](https://github.com/ds300/patch-package#set-up)), which seems contradictory.
It seems to me like `prepare` would be more appropriate, not sure what I'm missing.

@lawl, sorry for bothering you again, do you happen to know what I'm missing / how this is best fixed?

**Comment by lawl** [comment]
hmm, indeed weird. No I'm also not really familiar with patch package, I just googled how to do it with an npm project and stumbled upon this.

But the docs there say

    install, postinstall: Run AFTER the package is installed.

Maybe I'm misunderstanding, but this *should* be ran? I also might be misremembering but I think I nuked my `node_modules` to test if it's actually working. @streaps was this a clean checkout, or did you have the project build already and just `git pull; npm build`?

Because what's weird here is that the stack trace refers to `./node_modules/webworkify/index.js` when webworkify is a dependency that has been completely kicked, so it shouldn't even have been installed anymore.

**Comment by streaps** [comment]
@lawl: it was a clean checkout.

**Comment by Johni0702** [comment]
> Maybe I'm misunderstanding, but this should be ran?

Eh, yeah, the doc is really ambiguous. I think `npm install` (inside the folder of a local git checkout) and `npm install mumble-web` (inside the folder of another project) are two completely separate things (at least yarn has two distinct commands for those two actions) and when the doc says "is installed", it only refers to the later and not the former. Otherwise I'd be confused as to why it would have to be explicit about the `without any arguments` part in its description of `prepare`:
> […] on local npm install without any arguments […]

Really not too sure though.

**Comment by lawl** [comment]
Honestly, no clue then. I'd suggest just putting `npm run postinstall` in the docs, because this entire patch-package thing is already quite a hack as discussed in #70

**Comment by Johni0702** [comment]
Huh, this isn't getting any less confusing. I just tried building myself in a clean environment and just `npm install` did everything you could ever want it to do (i.e. install deps, invoke the postinstall script / patch-package and invoke the prepare script / webpack). Whereas in streaps' log it appears to just install deps and invoke neither postinstall nor prepare.

@streaps, do you know which version of npm you were using? Maybe it's just an older version that's broken.
In that case, the minimum npm version should probably go in the README instead, cause the current instructions don't actually work for me because the second invocation of patch-package (`npm run postinstall`) fails to apply the patches (cause they were already applied by `npm install`).

**Comment by streaps** [comment]
@Johni0702
npm 6.13.4
node 12.15.0

**Comment by Johni0702** [comment]
Hm, that's the same npm version and almost the same node version as I'm using, so that's probably not it.
Taking another closer look at your log, I noticed that it actually logs why it doesn't execute those scripts:
```
npm WARN lifecycle mumble-web@0.5.1~postinstall: cannot run in wd mumble-web@0.5.1 patch-package (wd=/root/repos/mumble-web)
npm WARN lifecycle mumble-web@0.5.1~prepare: cannot run in wd mumble-web@0.5.1 rm -rf dist && npm run build (wd=/root/repos/mumble-web)
```
Apparently, when invoked as root, npm will by default switch to the `nobody` user to run scripts and the nobody use cannot access `/root` (and couldn't run the scripts either cause they need to modify files which were just created by root).
So, AFAICT, you cannot build mumble-web as root. If you have the time, could you test if you can build mumble-web on the same machine as a non-root user?

**Comment by streaps** [comment]
🤦 I didn't know that I should not run it as root. Looks good now. `npm install` also does the build too.
